function y = cheby13_1(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 12-Apr-2018 13:16:17

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 12.8;  % First Stopband Frequency
    % Fpass1 = 12.9;  % First Passband Frequency
    % Fpass2 = 13.1;  % Second Passband Frequency
    % Fstop2 = 13.2;  % Second Stopband Frequency
    % Astop1 = 80;    % First Stopband Attenuation (dB)
    % Apass  = 1;     % Passband Ripple (dB)
    % Astop2 = 80;    % Second Stopband Attenuation (dB)
    % Fs     = 256;   % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.8973853921847 0.99986319142066; 1 0 -1 1 ...
        -1.90045812272018 0.999865203584327; 1 0 -1 1 -1.89732958514947 ...
        0.999606474799303; 1 0 -1 1 -1.90003449642784 0.999611568515827; 1 0 -1 ...
        1 -1.89748384189476 0.999398151866367; 1 0 -1 1 -1.89949318475704 ...
        0.999403943097141; 1 0 -1 1 -1.89782824685771 0.999263434753696; 1 0 -1 ...
        1 -1.89889797858116 0.999267214236998; 1 0 -1 1 -1.89831973062257 ...
        0.999218192522417], ...
        'ScaleValues', [0.00244834300666231; 0.00244834300666231; ...
        0.0021607966341003; 0.0021607966341003; 0.00162489646932765; ...
        0.00162489646932765; 0.000925723128467798; 0.000925723128467798; ...
        0.000390903738791398; 1]);
end

s = double(x);
y = step(Hd,s);

