function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 13-Apr-2018 09:40:23

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 25.6;  % First Stopband Frequency
    % Fpass1 = 25.8;  % First Passband Frequency
    % Fpass2 = 26.2;  % Second Passband Frequency
    % Fstop2 = 26.4;  % Second Stopband Frequency
    % Astop1 = 80;    % First Stopband Attenuation (dB)
    % Apass  = 1;     % Passband Ripple (dB)
    % Astop2 = 80;    % Second Stopband Attenuation (dB)
    % Fs     = 256;   % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.6003451066709 0.999726624379588; 1 0 -1 1 ...
        -1.61201048006952 0.999730209002574; 1 0 -1 1 -1.60064648160695 ...
        0.999213666270492; 1 0 -1 1 -1.61090695610093 0.999222738342851; 1 0 -1 ...
        1 -1.60164771317663 0.998797299409048; 1 0 -1 1 -1.60926458469128 ...
        0.998807611708921; 1 0 -1 1 -1.60322335670074 0.998527818298224; 1 0 -1 ...
        1 -1.60727664656461 0.998534547467192; 1 0 -1 1 -1.60517897777113 ...
        0.99843698662077], ...
        'ScaleValues', [0.00489633904990384; 0.00489633904990384; ...
        0.00432074462502433; 0.00432074462502433; 0.00324882713089298; ...
        0.00324882713089298; 0.00185077553835052; 0.00185077553835052; ...
        0.000781506689614944; 1]);
end

s = double(x);
y = step(Hd,s);

