function y = cheby17_1(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 12-Apr-2018 13:15:20

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 16.8;  % First Stopband Frequency
    % Fpass1 = 16.9;  % First Passband Frequency
    % Fpass2 = 17.1;  % Second Passband Frequency
    % Fstop2 = 17.2;  % Second Stopband Frequency
    % Astop1 = 80;    % First Stopband Attenuation (dB)
    % Apass  = 1;     % Passband Ripple (dB)
    % Astop2 = 80;    % Second Stopband Attenuation (dB)
    % Fs     = 256;   % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.82630565283276 0.999863447700837; 1 0 -1 1 ...
        -1.83027417589115 0.999864947303696; 1 0 -1 1 -1.82631327861815 ...
        0.999607123565655; 1 0 -1 1 -1.8298049496665 0.999610919746594; 1 0 -1 1 ...
        -1.82657643349833 0.999398889480747; 1 0 -1 1 -1.82916913666395 ...
        0.99940320547902; 1 0 -1 1 -1.82706208601569 0.999263916141753; 1 0 -1 1 ...
        -1.82844201167608 0.99926673284735; 1 0 -1 1 -1.8277102803792 ...
        0.999218192522417], ...
        'ScaleValues', [0.00244834300666275; 0.00244834300666275; ...
        0.00216079663410069; 0.00216079663410069; 0.00162489646932794; ...
        0.00162489646932794; 0.000925723128467964; 0.000925723128467964; ...
        0.000390903738791468; 1]);
end

s = double(x);
y = step(Hd,s);

