function y = cheby21_1(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 12-Apr-2018 13:17:43

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 20.8;  % First Stopband Frequency
    % Fpass1 = 20.9;  % First Passband Frequency
    % Fpass2 = 21.1;  % Second Passband Frequency
    % Fstop2 = 21.2;  % Second Stopband Frequency
    % Astop1 = 80;    % First Stopband Attenuation (dB)
    % Apass  = 1;     % Passband Ripple (dB)
    % Astop2 = 80;    % Second Stopband Attenuation (dB)
    % Fs     = 256;   % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.73763749026891 0.99986361079744; 1 0 -1 1 ...
        -1.74246378963358 0.999864784206877; 1 0 -1 1 -1.73770832095275 ...
        0.999607536439456; 1 0 -1 1 -1.74195363686333 0.999610506871396; 1 0 -1 ...
        1 -1.73807780523049 0.999399358893956; 1 0 -1 1 -1.74122948016781 ...
        0.999402736064005; 1 0 -1 1 -1.73870012931049 0.99926422249258; 1 0 -1 1 ...
        -1.7403773378716 0.999266426495754; 1 0 -1 1 -1.73949898100771 ...
        0.999218192522417], ...
        'ScaleValues', [0.00244834300666241; 0.00244834300666241; ...
        0.00216079663410039; 0.00216079663410039; 0.00162489646932771; ...
        0.00162489646932771; 0.000925723128467836; 0.000925723128467836; ...
        0.000390903738791414; 1]);
end

s = double(x);
y = step(Hd,s);

