function y = cheby0_1(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 12-Apr-2018 13:29:14

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fpass = 0.1;  % Passband Frequency
    % Fstop = 0.2;  % Stopband Frequency
    % Apass = 1;    % Passband Ripple (dB)
    % Astop = 80;   % Stopband Attenuation (dB)
    % Fs    = 256;  % Sampling Frequency
    %
    % h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 2 1 1 -1.99985820229713 0.999864197096532; 1 2 1 1 ...
        -1.99960435093143 0.999609020888565; 1 2 1 1 -1.9993984061701 ...
        0.999401047246619; 1 2 1 1 -1.99926446795029 0.999265325226367; 1 1 0 1 ...
        -0.999609020432101 0], ...
        'ScaleValues', [1.4986998505278e-06; 1.16748928327462e-06; ...
        6.602691293823e-07; 2.14319018772739e-07; 0.000195489783949643; 1]);
end

s = double(x);
y = step(Hd,s);

