function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 13-Apr-2018 09:41:30

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop1 = 33.6;  % First Stopband Frequency
    % Fpass1 = 33.8;  % First Passband Frequency
    % Fpass2 = 34.2;  % Second Passband Frequency
    % Fstop2 = 34.4;  % Second Stopband Frequency
    % Astop1 = 80;    % First Stopband Attenuation (dB)
    % Apass  = 1;     % Passband Ripple (dB)
    % Astop2 = 80;    % Second Stopband Attenuation (dB)
    % Fs     = 256;   % Sampling Frequency
    %
    % h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    %                      Fpass2, Fstop2, Astop1, Apass, Astop2, Fs);
    %
    % Hd = design(h, 'cheby1', ...
    %     'MatchExactly', 'passband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 0 -1 1 -1.33566561577062 0.999727211911523; 1 0 -1 1 ...
        -1.35017344309826 0.999729621468871; 1 0 -1 1 -1.33620549519153 ...
        0.999215153218579; 1 0 -1 1 -1.3489628897297 0.999221251383482; 1 0 -1 1 ...
        -1.3375818945571 0.998798989649105; 1 0 -1 1 -1.34705043562863 ...
        0.99880592145427; 1 0 -1 1 -1.33962481262566 0.998528921254256; 1 0 -1 1 ...
        -1.34466279951208 0.998533444504948; 1 0 -1 1 -1.34208442327133 ...
        0.99843698662077], ...
        'ScaleValues', [0.00489633904990382; 0.00489633904990382; ...
        0.00432074462502432; 0.00432074462502432; 0.00324882713089297; ...
        0.00324882713089297; 0.00185077553835051; 0.00185077553835051; ...
        0.000781506689614941; 1]);
end

s = double(x);
y = step(Hd,s);

